- mastodon/src/main/res/values-de-rDE/strings.xml
I added the translation strings for the federation timeline tab to the German translation file and also translated the values.
> Add German translation for the federated timeline

- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTimelineFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ThreadFragment.java
- mastodon/src/main/java/org/joinmastodon/android/model/Filter.java
- mastodon/src/main/java/org/joinmastodon/android/utils/StatusFilterPredicate.java
Follow up to #202
Found a bug where the app crashes when `expirationAt` field is null (filter do not expire).
While I was at it, made a small refactor.
> Better handling of filter expiration date

- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTimelineFragment.java
I've been experiencing a bug where, after the app is idle for a while, filtered ("hide") posts are appearing in the home timeline. I could not reproduce in debug mode, but it is happening somewhat consistently in the Play Store apk for me.
I guess it is related to empty `wordFilters` list as it's the only difference between manual refresh and auto refresh. Is it possible that we're not calling `maybeUpdateLocalInfo()`?
Anyway, I removed the `filters.isEmpty()` validation so status with `filtered` can still be checked. The semantics is the same as the constructor `StatusFilterPredicate(String accountID, Filter.FilterContext context)` still checks for `wordFilters`.
> Fix filtered posts showing during "auto refresh"

- mastodon/src/main/java/org/joinmastodon/android/fragments/SettingsFragment.java
- mastodon/src/main/res/values/strings_sk.xml
Adds a link to the about page of the home instance. Closes #261.
> feat(settings): add about instance link

- mastodon/src/main/java/org/joinmastodon/android/GlobalUserPreferences.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/SettingsFragment.java
- mastodon/src/main/res/values/strings_sk.xml
#317. Adds "re:" when replying to a CW'd post
> Prefix replies with "re:"

- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java
- mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
Fixes an issue, where the fourth menu item does not show up, when the divider is enabled on EMUI devices.
| Before                                                                                                           	| After                                                                                                           	|
|------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------	|
| ![Before](https://user-images.githubusercontent.com/63370021/224400191-cc28f8e6-b910-4077-95f7-4b82c003764f.png) 	| ![After](https://user-images.githubusercontent.com/63370021/224400198-17e3276a-0389-42f4-9c24-a1741ae99da1.png …
> fix: disable group divider on EMUI

- mastodon/src/main/res/layout/header_welcome_custom.xml
Changes the inputtype of the edittext on the welcome screen to `textUri`. This improves the experience of entering URLs, by adding a dedicated key to the keyboard.
> feat(welcome): use URI InputType

- mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
Fixes a bug, where the fab continued to work, even when being invisible. Credit goes to @LucasGGamerM for fixing it in https://github.com/LucasGGamerM/moshidon/commit/002edc889043b8081418e9d32a508149ee7df57c, although his fix does not work on the profile page, which is also included here.
> fix(fab): completly hide

- mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/MediaGridStatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/utils/MastodonLanguage.java
Both Calckey and GoToSocial would throw NullPointerExceptions when accessing notificaions. The markers field in the account session would be null and checking that beforehand seems to fix it
GoToSocial would also crash when trying to post because the language info was null
> Fix crashes on Calckey and GoToSocial

- mastodon/src/main/java/org/joinmastodon/android/api/CacheController.java
- mastodon/src/main/java/org/joinmastodon/android/api/requests/notifications/PleromaMarkNotificationsRead.java
- mastodon/src/main/java/org/joinmastodon/android/api/requests/timelines/GetBubbleTimeline.java
- mastodon/src/main/java/org/joinmastodon/android/api/requests/timelines/GetHashtagTimeline.java
- mastodon/src/main/java/org/joinmastodon/android/api/requests/timelines/GetPublicTimeline.java
- mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSession.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeTabFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/PinnableStatusListFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/SettingsFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ThreadFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/BubbleTimelineFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/TrendingHashtagsFragment.java
- mastodon/src/main/java/org/joinmastodon/android/model/Instance.java
- mastodon/src/main/java/org/joinmastodon/android/model/TimelineDefinition.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/HashtagStatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/ui/utils/DiscoverInfoBannerHelper.java
- mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
- mastodon/src/main/res/values/strings_sk.xml
This fixes and polishes some things for Akkoma/Pleroma instances
- Fix: Clicking links would sometimes result in opening an account page that wasn't meant to be opened
- Center hashtag in search when no history is present
- The things showed on the discover page aren't implemented on Akkoma so I made it just go straight to searching instead of showing empty lists
- Fix: Get the server's configured max amount of account fields and poll options properly
- Fix: Use Pleroma's api for marking notifications as read
I also started experiencing a problem some time ago where some users' quotes wouldn't display the "RE:" text and so I had to open it in the browser to see what was quoted. I did initially start implementing a proper UI for it, but it was then announced that it's coming to Mastodon so …
> More Akkoma/Pleroma improvements

- mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java
This would seemingly also corrupt the session and make the instance null when re-opening
> Fix GoToSocial crash when markers are null

- mastodon/src/main/AndroidManifest.xml
- mastodon/src/main/java/org/joinmastodon/android/ExternalShareActivity.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/onboarding/AccountActivationFragment.java
- mastodon/src/main/java/org/joinmastodon/android/ui/AccountSwitcherSheet.java
- mastodon/src/main/res/layout/item_account_switcher.xml
- mastodon/src/main/res/values/strings_sk.xml
- mastodon/src/main/res/values/styles.xml
Upstreams https://github.com/LucasGGamerM/moshidon/pull/125 (which depends on https://github.com/LucasGGamerM/moshidon/pull/121).
This redesign the share dialog to be use the  `AccountSwitcherSheet`. It then adds a new option to open shared URLs directly in the app. The option will only be visible when the URL is a Mastodon URL.
> feat: share to open url

- mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java
Fixes https://github.com/sk22/megalodon/issues/595, by setting the chips as a list of tags and not a singular tag.
| Before                                                                                                          	| After                                                                                                            	|
|-----------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------------------------------------------------	|
| ![Tags a singular chip](https://github.com/sk22/megalodon/assets/63370021/fcfb9a16-2bee-4c8a-92e3-d00691333778) 	| ![Tags a multiple chips](https://github.com/sk22/megalodon/assets/63370021/17943d4d-3764-4e57-b300-354 …
> fix(edit-timelines/hashtags): set tags as list

- mastodon/src/main/java/org/joinmastodon/android/api/requests/timelines/GetHashtagTimeline.java
Fixes multi tag timelines by correctly adding multiple hashtags. When constructing a request, all tags were added as a comma-separated list, e.g. `https://floss.social/api/v1/timelines/tag/Megalodon?any[]=Android,MastodonApp`. This would work for the first tag, but all subsequent tags would be ignored. The correct query would be `https://floss.social/api/v1/timelines/tag/Megalodon?any[]=Android&any[]=MastodonApp`.
> fix(hashtag-timeline): add additional tags as separated parameter

- mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/SearchFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsMainFragment.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/ui/viewcontrollers/ComposePollViewController.java
I noticed that some of my previous PRs related to Akkoma hadn't survived the move to the m3 redesign, so I decided to re-implement what was missing
While I was at it I also made the filter settings page hidden while using an Akkoma account because it would just give an error, and this app doesn't even support Akkoma's filter system anyways
> Re-implement some Akkoma specific things + hide filter settings

- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/HeaderStatusDisplayItem.java
Same issue as in https://github.com/sk22/megalodon/pull/453, with the `Copy link to post` option being invisible on EMUI. Disabling should fix it.
> fix: copy link invisible on EMUI

- mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java
Expands the `openURL` function to also open `/about` links in-app, in the new `SettingsServerFragment`.
https://github.com/sk22/megalodon/assets/63370021/799c7468-fd6a-4dd8-b755-d30e3a79c41b
> feat(openURL): open about in app

- mastodon/src/main/java/org/joinmastodon/android/fragments/account_list/PaginatedAccountListFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsServerAboutFragment.java
- mastodon/src/main/java/org/joinmastodon/android/ui/viewholders/AccountViewHolder.java
When opening a remote profile via the Following/Followers list, the profile shows correctly, but the status fails to load due to the ID being incorrect. This is a regression in M3 merge and can be fixed by sending the account as a remoteAccount.
| Before                                                                                                   	| After                                                                                                               	|
|----------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------	|
| ![Empty Profile](https://github.com/sk22/megalodon/assets/63370021/06904a59-5ad5-4ce9-8af8-87f …
> fix(remote): send remoteAccount

- mastodon/build.gradle
- mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java
Follow-up to https://github.com/sk22/megalodon/pull/749, adding a new build flavor for f-droid, which disables notification registration using FCM. This would allow Megalodon to be distributed over F-Droid without the `NonFreeNet` anti-feature.
See https://github.com/LucasGGamerM/moshidon/issues/206 for more context.
> build: add F-Droid flavor

- mastodon/src/main/java/org/joinmastodon/android/ui/viewholders/AccountViewHolder.java
Fixes a missing string placeholder when long pressing a username in the detailed post info screen.
| Before                                                                                                                           	| After                                                                                                                         	|
|----------------------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------------------	|
| ![Display lists with Placeholder](https://github.com/LucasGGamerM/moshidon/assets/63370021/c83ff603-4f81-426b-afe0-370c7c5fa5d1) 	| ![Display lists with …
> fix: display 'Lists with' placeholder

- mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSession.java
The `AccountSession.preferencesFromAccountSource` method would only work if the `preferences` field wasn't null, but that would only be the case either if the GetPreferences endpoint succeeded or the user had changed the default posting language
This function is really only useful for accounts that don't have the GetPreferences endpoint, so it should also be set properly when the endpoint gives an error (without the user manually having to change language)
> Fix unreliable Preferences from Account Source

- mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java
This fixes the bug where you cannot edit timeline badges
> fix: allows for editing timeline badges again. fixes sk22#800

- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
- mastodon/src/main/res/layout/tab_bar.xml
Moves the tabbar padding from the tabbar to the individual tabbar items.
This fixes the issue where the spaces below the items is not clickable (does not select a tab), which is especially noticeable when disabling the labels.
> fix: move tabbar padding to tabbar items

- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/SearchQueryFragment.java
This happens when you tap on a recent search and the current query is null. This is caused by the suicide help prevention dialog not checking if the currentQuery is null before trimming it. This addresses that issue
> fix: fixes crashes when currentQuery is null and suicide prevention dialog is enabled

- mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java
Closes https://github.com/sk22/megalodon/issues/803 and https://github.com/LucasGGamerM/moshidon/issues/254. This was due to registering with the actual account ID while saving a random one. After receiving a notification, the ID could not be found compared to the saved random one, so no notification was displayed.
The problem only occurred when a user tried to re-register with FCM, either by switching from Unified Push or by changing the notification settings, so only some users were affected.
> fix: use random account id in notification endpoint

- mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java
This fixes a bug where you would reply to a mentioned-only post from the notification and the reply would be set to public.
> Fix notifications replies visibility/language not being consistent with replied status

- mastodon/src/main/java/org/joinmastodon/android/fragments/EditTimelinesFragment.java
Fixes https://github.com/sk22/megalodon/issues/595 again, as the fix in https://github.com/sk22/megalodon/pull/596 seems to have been lost in the M3 merge.
| Before                                                                                                                     	| After                                                                                                                   	|
|----------------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------------	|
| ![Advanced UI with single chip](https://github.com/sk22/megalodon/assets/63370021/1eb7b433-86ce-4392-a465-ca868c2794c1) 	| ![Advanced UI …
> fix: show individual chips

- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/TextStatusDisplayItem.java
This fixes a crash that happens from time to time on the timeline where the translate system would try to know what language a status has, but the status has no language
> fix(translations): fix crash when status language is null

- mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java
This fixes a crash where the follow button menu item would try to find whether or not the hashtag was followed, causing a dereference of a null object. The follow menu item still works as expected though, as the updating is being done by the updateHeader() method.
> fix(hashtags): fix crash when hashtag is null

- mastodon/src/main/java/org/joinmastodon/android/fragments/HashtagTimelineFragment.java
This is caused by calling TimelineDefinition.of(hashtag), where the hashtag was previously a String, but its now a Hashtag. But by consequece, hashtag can be null. This addresses that by using hashtagName instead of hashtag
> fix(hashtag-fragment): fix crash when opening some hashtags

- mastodon/src/main/java/org/joinmastodon/android/fragments/HomeFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/discover/DiscoverFragment.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsMainFragment.java
There was a bug in my previous PR for hiding the discovery page on Akkoma where it would still show if the instance info hadn't been fetched before it tried to find out if it should hide discovery. It seems like it always will have this info when running onCreateView for the discovery fragment instead of onCreate for the home fragment
New settings were introduced recently for some new Mastodon privacy options, but Akkoma doesn't have these. It does have one that's similar that's also called discoverable, but it's located in a different place in the API, and it's also not fully the same. From my understanding, Mastodon's setting is about Mastodon search while Akkoma's is about external search engines, so the setting would probably need a different implementation in Megalodon for it to make …
> fix: hiding discovery on Akkoma + hiding privacy settings

- mastodon/src/main/java/org/joinmastodon/android/ui/viewcontrollers/ComposePollViewController.java
Restores the 12-hour poll option that was previously added to https://github.com/sk22/megalodon/pull/346, but no longer available in the latest release.
> feat: re-add 12 hour option to polls

- mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsNotificationsFragment.java
Currently, when toggling on/off UnifiedPush, only the current account is getting (un)registered. And new account don't get registered. This PR fixes this.
> Fix: registering multi account for UnifiedPush

- mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSession.java
When receiving a push notification while the app is killed, `filterStatusContainingObjects` is called and it uses `localPreferences` before it is initialized and causes a NullPointerException. This PR changes `AccountSession.class` so `getLocalPreferences` is always called to be sure `localPreferences` is initialized.
---
logcat:
```
2023-10-30 19:38:56.860 16727-16727 AndroidRuntime          pid-16727                            E  FATAL EXCEPTION: main
Process: org.joinmastodon.android.sk.debug, PID: 16727
java.lang.NullPointerException: Attempt to read from field 'boolean org.joinmastodon.android.api.session.AccountLocalPreferences.serverSideFiltersSupported' on a null object reference in method 'void org.joinmastodon.android.api.session.AccountSession.filterStatusContainingObjects(java. …
```
> Fix NullPointerException when receiving push when killed

- mastodon/src/main/java/name/fraser/neil/plaintext/LICENSE
- mastodon/src/main/java/name/fraser/neil/plaintext/diff_match_patch.java
- mastodon/src/main/java/org/joinmastodon/android/api/requests/statuses/GetStatusEditHistory.java
- mastodon/src/main/java/org/joinmastodon/android/fragments/StatusEditHistoryFragment.java
- mastodon/src/main/java/org/joinmastodon/android/model/Status.java
- mastodon/src/main/java/org/joinmastodon/android/ui/text/DiffRemovedSpan.java
- mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java
Improves the status edit history by highlighting the text changes that have been made, closing https://github.com/sk22/megalodon/issues/789.
It uses [google's diff-match-path library](https://github.com/google/diff-match-patch), added text is shown in green, while removed text is shown in red with a strikethrough.
It also fixes a problem where the history could not be loaded if the status had a poll, because the poll ID was null.
There are still a few edge cases, such as HTML parsing breaking when a tag was edited. I'm not quite sure what the best solution is to fix this.
Also, the colors may need to be adjusted, as it may be hard to see single character edits in longer posts.
> feat: display edit history diff

- mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
- mastodon/src/main/java/org/joinmastodon/android/model/Translation.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/MediaGridStatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/PollOptionStatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/SpoilerStatusDisplayItem.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java
Adds the ability to translate not only status text, but also media attachment descriptions (alt text) and poll options, a new feature introduced in [4.2.0](https://github.com/mastodon/mastodon/releases/tag/v4.2.0).
| Untranslated                                                                                                       	| Translated                                                                                                      	|
|--------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------------------------------------------	|
| ![Untranslated poll](https://github.com/sk22/megalodon/assets/63370021/0140f438-2a78-4cc2-bbdc-921857d72147) 	| …
> feat: translate media attachments and poll options

- mastodon/src/main/java/org/joinmastodon/android/model/Card.java
- mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java
Hides the link card generated by Akkoma instances for hashtags in posts. This will only happen if the card URL points to the same server, starts with `/tag/`, and has `Akkoma` as the title.
This is an improvement for both newer users, who may be confused by a link card appearing without a link, and experienced users, who may be annoyed by an unnecessary link card.
| Before                                                                                                         	| After                                                                                                              	|
|----------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------------------ …
> fix: hide link card to akkoma hastags
